### ISSUE TITLE
How to generate the mobilenet.mlmodel file?

### ISSUE THREAD

**Issue by chriszeng87** [infocom-tpo/SwiftOpenPose#1]
Thank you for this awesome project! 
When I compile the project, I got this error:
coremlc: Error: unable to read document: /Users/qyvideo/work/deep_learning/SwiftOpenPose/SwiftOpenPose/Resources/mobilenet.mlmodel
detail: validator error: unable to open file for read
and how to generate this file? Is it in this section:
OpenPose Keras Mobilenet-Model
Result: However it did not work.

**Comment by mbotsu** [comment]
Thank you for trying.

You need to create a model converted from Caffe-Model to MLModel with reference to the next section.
https://github.com/infocom-tpo/SwiftOpenPose/blob/master/doc/CaffeToMLModel.md

Apart from that, I can try out a model trained with the high speed mobilenet layer that we will release today.
https://s3-ap-northeast-1.amazonaws.com/swiftopenpose/MobileOpenPose.mlmodel

thank.

**Comment by chriszeng87** [comment]
Cool!
