### ISSUE TITLE
What is the bin file in 'Resources' directory?

### ISSUE THREAD

**Issue by chriszeng87** [infocom-tpo/SwiftOpenPose#2]
I want to use this to detect body in my custom picture. but after I drag it into the Resources directory and change a little bit here:
        let fname = "test.jpg"
It seems the app didn't respond and can not detect where the body is.
I noticed there are two bin files(hadou.bin and person1.bin). Should I generate a bin file first for my custom picture?

**Comment by mbotsu** [comment]
It is not necessary to create a bin file.
Is there a check in Target-Membership?
<img width="136" alt="targetmembership" src="https://user-images.githubusercontent.com/33709712/34353395-2681c79c-ea6b-11e7-8ff7-c088c801cd20.png">

**Comment by chriszeng87** [comment]
So sorry, it seems I made a stupid mistake. Thank you for your explanation.
