### ISSUE TITLE
How can i run this project with XCode?

### ISSUE THREAD

**Issue by hannesoud** [infocom-tpo/SwiftOpenPose#5]
Screenshots:
http://prntscr.com/hxh7vg
http://prntscr.com/hxh7zc

XCode 9.2

**Comment by mbotsu** [comment]
Thank you for trying.
You need to set up a library of dependencies with different licenses.

**Comment by EricTheAI** [comment]
@mbotsu  Thanks for your reply. I had the same issue but I'm still confused about "set up a library of dependencies with different licenses", could you kindly give more hints on this? Thanks a lot!

**Comment by mbotsu** [comment]
OK. Now I made it installable in the pod.
```
$ git clone https://github.com/infocom-tpo/SwiftOpenPose.git
$ cd SwiftOpenPose
$ pod install
```
Thanks.

**Comment by EricTheAI** [comment]
@mbotsu Thanks so much for your help! I'm a beginner in iOS development and what you did really help a lot.
