### ISSUE TITLE
How to integrate camera with this project

### ISSUE THREAD

**Issue by mohitkotie** [infocom-tpo/SwiftOpenPose#6]

**Comment by mbotsu** [comment]
Thanks to Issue.
But it is not a theme to deal with here.
Please check about [AVCaptureSession](https://developer.apple.com/documentation/avfoundation/avcapturesession).

This example may be helpful.
https://github.com/infocom-tpo/SwiftOpenPose/blob/master/examples/BoneDetecter/BoneDetecter/ViewController.swift
