### ISSUE TITLE
BoneDetecter did not work. Compile error.

### ISSUE THREAD

**Issue by seijichishiki** [infocom-tpo/SwiftOpenPose#7]
Thank you for this project.
When I compile the example BoneDetecter, I got this error:
```
./examples/BoneDetecter/Pods/Upsurge/Sources/Upsurge/ValueArray.swift:134:35: Missing argument for parameter 'capacity' in call
./examples/BoneDetecter/Pods/Swift.UnsafeMutablePointer:273:17: 'deallocate(capacity:)' declared here

```
How can I run BoneDetecter ?

Infocomさんは、確か日本だったかと思いますので、日本語でも記入させていただきます。
すみません、exampleにあるBoneDetecterを動かそうと思い、コンパイルすると、上記のエラーとなります。
何が原因だかお分かりになるでしょうか？
xcode9.2 です。Upsurge、IteratorTools、OpenCVは、ルートフォルダにあったPodファイルを改変作成してインストールしています。
```
  pod 'Upsurge', '~> 0.10.0'
  pod 'IteratorTools', '~> 1.1.0'
  pod 'OpenCV', '~> 3.3.1'
```
よろしくお願いします。

**Comment by medmsyk** [comment]
Thank you for asking.
Sorry, but you need to change versions of the libraries.
Please refer to the settings below.

ご質問頂き、有難うございます。
申し訳ありませんが、ライブラリのバージョンを変える必要があります。
以下のように変更してからインストールして頂けますでしょうか。

Xcode 9.3
```
pod 'Upsurge', '0.10.2'
pod 'IteratorTools', '1.1.0'
pod 'OpenCV', '3.3.1'
```

Xcode 9.0 - 9.2
```
pod 'Upsurge', '0.10.0'
pod 'IteratorTools', '1.1.0'
pod 'OpenCV', '3.3.1'
```

**Comment by seijichishiki** [comment]
Thank you  very much. The BoneDetecter did work !

お忙しい中、ありがとうございました。無事コンパイル通りました。
素晴らしいプロジェクトに感謝いたします。
