### ISSUE TITLE
An issue for compile

### ISSUE THREAD

**Issue by chen-xi-wang** [infocom-tpo/SwiftOpenPose#8]
Hi! After I compiled SwiftOpenPose.xcworkspace succeed on Xcode for my iPhone 6s,  while I opening the app, it seems like stuck on the image(swiftopenpose_result.png) that on the /SwiftOpenPose/images. Do you know what happened?
Thanks

**Comment by chen-xi-wang** [comment]
And for the other issue about BoneDetecter, I create the Podfile and excute "pod install" at the root directory of BoneDecter. 

pod 'Upsurge', '0.10.2'
pod 'IteratorTools', '1.1.0'
pod 'OpenCV', '3.3.1'

and then execute"curl -o BoneDetecter/Resources/MobileOpenPose.mlmodel https://s3-ap-northeast-1.amazonaws.com/swiftopenpose/MobileOpenPose.mlmodel

Finally, It shows compile error: CoreML Model Compile Error: unable to read document:MobileOpenPose.mlmodel
Could you please give me some ideas? Thank you very much.

**Comment by mbotsu** [comment]
Thank you for trying.

> Hi! After I compiled SwiftOpenPose.xcworkspace succeed on Xcode for my iPhone 6s, while I opening the app, it seems like stuck on the image(swiftopenpose_result.png) that on the /SwiftOpenPose/images. Do you know what happened?

There is only the function to predict joints from images.
Please try and change the loading image.

> Could you please give me some ideas? Thank you very much.

Have you tried Pods Import ?
<img width="266" alt="pods_import" src="https://user-images.githubusercontent.com/33709712/39689966-7a53084e-5213-11e8-91af-088bc8e027e1.png">

**Comment by chen-xi-wang** [comment]
Yes. I had tried command "pod install" to import the Upsurge, iteratorTools, and openCV2.framework. But do not know why there are still exist red names for the dependencies library(shown as figure). And I can run it on my device at the first time succeed after compile it. 

However, at the second time, it doesn't work. It seems like stuck on the step that processing(0%) with black background after I choose a video from local Albums. Otherwise, the same issue existing when I Profile this project with instrument 6. 

The goal of my research is to analyze the performance of the main functions with different CPU usage. If you could give me some suggestions, that would be much helpful ! Thanks a lot. 
![12](https://user-images.githubusercontent.com/28569870/41266947-48f99752-6dc7-11e8-9e0d-b0f0fccad089.png)

**Comment by otmb** [comment]
Delete the red library. These are included in the pod.

**Comment by mbotsu** [comment]
Delete the red library. These are included in the pod.

**Comment by chen-xi-wang** [comment]
Ok. Thanks for your reply. I already delete the red library and restart the Xcode. But the previous issue seems still exist. The fisrt figure is Profile "Core Animation" result, there is an error"mach_msg_trap". The second figure is the error that when I running it on my device. 

```
2018-06-11 23:10:00.003372-0400 BoneDetecter[2271:1056186] Status bar could not find cached time string image. Rendering in-process.
2018-06-11 23:10:02.448986-0400 BoneDetecter[2271:1056286] [discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
```

![2](https://user-images.githubusercontent.com/28569870/41268171-de3edcaa-6dcc-11e8-8d75-c619cf7f2369.png)
![4](https://user-images.githubusercontent.com/28569870/41268400-de4fcc80-6dcd-11e8-9ef6-90680409ef71.png)

**Comment by mbotsu** [comment]
I updated to Xcode 9.4 and confirmed its operation.
It moves without problems.
I can not find OpenCV in the image, but have you specified OpenCV in Pod?

**Comment by chen-xi-wang** [comment]
yes, I think so. I created Podfile for BoneDetecter as following:
```
platform :ios, '11.0'
target 'BoneDetecter' do
  use_frameworks!

  # Pods for BoneDetecter
  pod 'Upsurge', '~> 0.10.2'
  pod 'IteratorTools', '~> 1.1.0'
  pod 'OpenCV', '~> 3.4.1'

end
```

In case any other unexpected error, I rebuild the BoneDetecter project from scratch. 
step 1: git clone. Create Podfile(shown above) on root dir, and "pod install"
step 2: copy "MobileOpenPose.mlmodel" from /SwiftOpenPose/Resources to /BoneDetecter
step 3: open the BoneDetecter.xcworkspace through Xcode, delete the red library, since they are included in the Pod. And then build it succeed and Profile it. 

The previous issue is still exist. Profile "Core Animation" result, there is an error"mach_msg_trap". It seems like stuck on the step that processing(0%) with black background after I choose a video from local Albums. 
I am stuck this point for a couple of days, please help!
Thanks!

![wx20180614-112512](https://user-images.githubusercontent.com/28569870/41421841-a2bcbc06-6fc5-11e8-9976-b83e7dca5941.png)

**Comment by mbotsu** [comment]
Hi.
Some cooperation is necessary to identify the problem.
- Please tell me the device you are using.
- Will the problem occur even if I change to another movie?
- Please tell me the extension of the video you evaluated.
- The library used for BoneDetector has not been updated for a while.
  Does the same problem occur in "Stickman Animator" of iTuensStore?
  https://itunes.apple.com/jp/app/stickman-animator/id1337589939?mt=8

**Comment by chen-xi-wang** [comment]
Sure. 
- I use iPhone 6s, iOS 11.4 version. 
- Yes, I had tried different video, whether take fresh video or pick local video, this issue occur always.
- The extension of the sample video is .MOV. It is a 10 seconds video with 720p at 30 fps.
- No, the Stickman Animator works fine. The problem just occurred when I Profile the example project "BoneDetecter". For the SwiftOpenPose project, it also works perfect. That makes me confused. 

Thanks!

**Comment by mbotsu** [comment]
I am late.
Phenomena could be reproduced with iPhone 6s.
I fixed it, so please try it.
Thank you!

https://github.com/infocom-tpo/SwiftOpenPose/commit/9745c0074dfe7d98265a325e25d2e2bb3d91d3d1

**Comment by chen-xi-wang** [comment]
Ok. I will try it right now. Thank you so much!

On Jun 14, 2018, at 1:03 PM, Manabu Otsu <notifications@github.com<mailto:notifications@github.com>> wrote:


I am late.
Phenomena could be reproduced with iPhone 6s.
I fixed it, so please try it.
Thank you!

9745c00<https://github.com/infocom-tpo/SwiftOpenPose/commit/9745c0074dfe7d98265a325e25d2e2bb3d91d3d1>

**Comment by chen-xi-wang** [comment]
Made it! 
Appreciate your help! 
Thanks a lot!
